### ISSUE TITLE
Issue archiving with Xcode 15

### ISSUE THREAD

**Issue by lilidotshi** [gonzalezreal/NetworkImage#32]
I'm trying to use your library for SwiftUI markdown, and I've narrowed the problem to this particular SPM. When we try to archive, we consistently get the error `error: ld: unknown option: -no_warn_duplicate_libraries`. Removing this particular package gets rid of the error. Hoping you can shed some light on this

**Comment by gonzalezreal** [comment]
Hi @lilidotshi,

There is nothing special about the NetworkImage package. It doesn't have any dependencies and it's used directly or indirectly in published apps without any issues.

Could this issue be related with your build configuration and/or toolchain?

**Comment by lilidotshi** [comment]
Hi yes, it appears that the error went away with removing references to ld_classic and adding “-Wl,-no_warn_duplicate_libraries” to linker flags
